Feature/rounded corners clipping
zawadz88/MaterialPopupMenu pull request #47
Opened 2019-04-14 18:03 UTC by Tunous

This change allows users to use custom items that have colored background and also use a popup with rounded corners.

Before the changes, the popup wouldn't display rounded corners for the custom view because its background wasn't clipped and it was drawing outside of the area of rounded drawable. After the change, when drawing, the content is properly clipped to the area of the background drawable and thus rounded corners work correctly.

___

I've also added sample for the rounded corners but unfortunately you can't see in it how I've fixed the corners issue. That's because the default view adds top and bottom padding which prevents the item from appearing at the edge of popup where the issue would be present. Although, that can be fixed if #44 gets merged so we can then set that vertical padding to 0.

Anyway here is how it looks right now:

<img src="https://user-images.githubusercontent.com/5156340/56097059-fc06a780-5eef-11e9-9ff6-4bf18192a0ce.png" height="580" />

2019-04-14 18:23 UTC, Tunous commented
This change basically makes it possible to implement background like this:

<img src="https://user-images.githubusercontent.com/5156340/56097337-f3fc3700-5ef2-11e9-8914-509cb6815648.png" height="580" />

_Note that this screenshot uses features from all my pull requests combined 😄_

2019-04-15 15:11 UTC, zawadz88 requested changes
This seems to be working on newer OS versions (I've checked on Oreo 8.1 so far) but there's an issue on KitKat where the popup cannot be dismissed by clicking on the outside nor by clicking system Back button. Also, the overscroll effect looks a bit off with the shadow appearing outside of the popup content.
Sample attached:
![clipping](https://user-images.githubusercontent.com/3322260/56143307-96262880-5fa0-11e9-8f9b-6c5ce9d866eb.gif)

Also, on both Android 8.1 and 4.4 I've noticed that "Custom colors" sample seems to be broken (incorrect background):
![Screenshot_1555340891](https://user-images.githubusercontent.com/3322260/56143725-53b11b80-5fa1-11e9-848c-6dcb745b1b38.png)

2019-04-15 15:48 UTC, Tunous commented
Good finds. I usually don't support these earlier versions of Android in my apps anymore so I forgot to test on them. Will try to fix the mentioned issues and test it properly.

2019-04-15 16:32 UTC, Tunous commented
I've fixed the problem with background color. I didn't see that you could customize it separately so now I'm simply moving the background from popup to RecyclerView so everything will look like before and clipping will work.

Unfortunately for KitKat I'm not sure if it's possible to fix clipping issue here. Plus the rounded background for that version looks terrible due to missing shadow. So I've just went ahead and disabled rounded corners sample for per-lollipop versions. I don't have other ideas...

2019-04-15 16:34 UTC, Tunous commented
Oh and here is sample with proper padding now:

<img src="https://user-images.githubusercontent.com/5156340/56149566-22d6e380-5fad-11e9-82fd-915136ffcfa2.png" height="580" />

2019-04-15 18:02 UTC, zawadz88 commented
For KitKat the solution would be to prepare a custom 9-patch with rounded corners + have the bottom/tip items in the list also use a background with rounded corners. However, I think that might a bit too much for a sample app.

2019-04-16 14:48 UTC, zawadz88 approved these changes

2019-04-16 14:48 UTC, merged